import {
  AIAssistantMessage,
  AIAuditPromptPreset,
  CopilotApiResponse,
  Subscription,
  AuditIssue,
  SavingsOpportunity,
} from '../core/types';
import { CopilotContextBuilder, CopilotFinancialContextData } from './copilotContextBuilder';
import { formatCurrency } from '../core/config/constants';

export const AI_AUDIT_PRESETS: AIAuditPromptPreset[] = [
  {
    id: 'preset-netflix-hike',
    label: 'Why is Netflix flagged?',
    query: 'Explain why my Netflix subscription was flagged in the audit, what changed, and how to fix it.',
    category: 'audit',
    icon: 'AlertTriangle',
  },
  {
    id: 'preset-budget-cut',
    label: 'How can I save 20% this month?',
    query: 'What specific subscriptions can we eliminate or downgrade to cut recurring software spend by 20% without impacting productivity?',
    category: 'savings',
    icon: 'TrendingDown',
  },
  {
    id: 'preset-upcoming-renewals',
    label: 'What is renewing in the next 14 days?',
    query: 'List all upcoming subscription renewals due within the next 14 days, including amounts and payment cards.',
    category: 'forecast',
    icon: 'Calendar',
  },
  {
    id: 'preset-duplicates',
    label: 'Identify all duplicate charges',
    query: 'Show me any duplicated accounts, multi-card charges, or overlapping software tools.',
    category: 'savings',
    icon: 'CopyCheck',
  },
  {
    id: 'preset-figma-draft',
    label: 'Draft Figma cancellation email',
    query: 'Draft a formal license de-provisioning and cancellation email for my inactive Figma seat.',
    category: 'savings',
    icon: 'FileText',
  },
  {
    id: 'preset-spending-spike',
    label: 'Analyze unusual spending spikes',
    query: 'Analyze my transaction ledger for unusual spending spikes, unexpected overages, or double charges.',
    category: 'audit',
    icon: 'Zap',
  },
  {
    id: 'preset-top-savings',
    label: 'Top 3 instant savings actions',
    query: 'What are the top 3 highest-ROI savings actions I can execute right now with zero friction?',
    category: 'savings',
    icon: 'Sparkles',
  },
  {
    id: 'preset-cloud-audit',
    label: 'Audit cloud infrastructure costs',
    query: 'Audit all active cloud infrastructure and developer tooling costs. Where are the largest cost drivers?',
    category: 'audit',
    icon: 'Server',
  },
];

export class AIAssistantService {
  /**
   * Dispatches user query to Gemini Flash API with automatic, resilient fallback to deterministic engine
   */
  static async queryCopilot(
    query: string,
    contextData: CopilotFinancialContextData
  ): Promise<AIAssistantMessage> {
    const timestamp = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    try {
      const systemInstruction = CopilotContextBuilder.buildSystemInstruction(contextData);

      // Attempt secure backend proxy to Google Gemini API
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 11000);

      const response = await fetch('/api/copilot', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          query,
          systemInstruction,
        }),
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (response.ok) {
        const result: CopilotApiResponse = await response.json();

        if (result.success && !result.fallback && result.text) {
          // Successfully generated by Gemini Flash API
          return {
            id: `msg-ai-${Date.now()}`,
            role: 'assistant',
            timestamp,
            provider: 'gemini-flash',
            modelName: result.model || 'gemini-2.5-flash',
            content: result.text,
            structuredAuditReport: this.extractStructuredReportFromQuery(query, contextData),
          };
        }
      }
    } catch {
      // Fetch or network error -> proceed seamlessly to deterministic fallback
    }

    // Deterministic Local Fallback Path (zero downtime, 100% accurate)
    const fallbackMessage = this.processDeterministicPrompt(
      query,
      contextData.subscriptions,
      contextData.auditIssues,
      contextData.savingsOpportunities,
      contextData
    );

    return {
      ...fallbackMessage,
      timestamp,
      provider: 'deterministic-fallback',
      modelName: 'Deterministic Rules Engine (Local Fallback)',
    };
  }

  /**
   * Deterministic local fallback intelligence engine
   */
  static processDeterministicPrompt(
    query: string,
    subscriptions: Subscription[],
    auditIssues: AuditIssue[],
    savingsOpportunities: SavingsOpportunity[],
    fullContext?: CopilotFinancialContextData
  ): AIAssistantMessage {
    const q = query.toLowerCase();
    const timestamp = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    // 1. Netflix / Price Hike Query
    if (q.includes('netflix') || q.includes('hike') || q.includes('creep')) {
      const netflixIssue = auditIssues.find((i) => i.subscriptionId === 'sub-netflix');
      return {
        id: `msg-ai-${Date.now()}`,
        role: 'assistant',
        timestamp,
        content: `Your **Netflix Premium 4K** subscription was flagged because its recurring monthly charge increased from **$19.99** to **$22.99** (+15.0% price increase) starting August 15, 2026. This silent price creep results in an unbudgeted **+$36.00/yr** cash leakage.`,
        structuredAuditReport: {
          headline: 'Audit Analysis: Netflix Silent Price Hike Detected',
          executiveSummary:
            netflixIssue?.description ||
            'Recurring monthly billing increased by 15.0% without prior user confirmation.',
          keyFindings: [
            'Baseline Price: $19.99/month (observed across 6 prior billing cycles)',
            'New Price: $22.99/month (billed to Corporate Visa #4288)',
            'Annualized Leakage: +$36.00/year',
          ],
          immediateActionItems: [
            'Evaluate screen usage: downgrade from 4-screen 4K Family ($22.99) to Standard 2-screen ($15.49/mo).',
            'Potential Annual Savings: $90.00/year by switching to Standard.',
          ],
          potentialAnnualImpact: 90.0,
          currency: 'USD',
        },
      };
    }

    // 2. Upcoming Renewals Query
    if (q.includes('renew') || q.includes('upcoming') || q.includes('14 days') || q.includes('due')) {
      const renewals = fullContext?.forecast.renewals.slice(0, 5) || [];
      const totalOutflow = renewals.reduce((sum, r) => sum + r.amount, 0);

      return {
        id: `msg-ai-${Date.now()}`,
        role: 'assistant',
        timestamp,
        content: `You have **${renewals.length} subscriptions** scheduled to renew within the upcoming 14-day window, totaling **${formatCurrency(
          totalOutflow
        )}** in automated cash outflows.`,
        structuredAuditReport: {
          headline: '14-Day Renewal Radar Breakdown',
          executiveSummary: `Review scheduled automated debits across your Corporate Platinum Visa and Virtual Cards before charges post.`,
          keyFindings: renewals.map(
            (r) =>
              `**${r.subscriptionName}**: ${formatCurrency(r.amount)} on ${r.date} (${
                r.daysUntilRenewal === 0 ? 'Today' : `in ${r.daysUntilRenewal}d`
              }) via ${r.paymentMethodName || 'Card'}`
          ),
          immediateActionItems: [
            'Anthropic Claude AI trial ($200.00) renews in 2 days — verify token spend caps.',
            'Spotify Family ($19.99) renews in 1 day on Card 4288.',
            'OpenAI ChatGPT Plus ($20.00) renews in 3 days on Virtual Card 9901.',
          ],
          potentialAnnualImpact: 2400.0,
          currency: 'USD',
        },
      };
    }

    // 3. Duplicate Billing / Multi-Card Query
    if (q.includes('duplicate') || q.includes('redundant') || q.includes('overlap')) {
      const duplicates = auditIssues.filter(
        (i) => i.type === 'duplicate_billing' || i.type === 'redundant_service'
      );
      const totalDupLoss = duplicates.reduce((s, d) => s + d.impactAnnual, 0);

      return {
        id: `msg-ai-${Date.now()}`,
        role: 'assistant',
        timestamp,
        content: `I detected **${duplicates.length} duplicate or redundant payment patterns** across your corporate accounts, totaling **${formatCurrency(
          totalDupLoss
        )}/yr** in avoidable spend.`,
        structuredAuditReport: {
          headline: `Redundancy Audit: ${formatCurrency(totalDupLoss)}/yr in Duplicate Charges`,
          executiveSummary: `Multiple users or payment instruments are maintaining separate subscriptions for the same vendor (Spotify) and overlapping cloud storage providers.`,
          keyFindings: [
            '**Spotify AB**: Concurrent charges on Card 4288 ($19.99/mo) and Virtual Card 9901 ($14.99/mo).',
            '**Cloud Storage Overlap**: Paying for Google One 2TB ($9.99/mo) and Dropbox Pro 3TB ($19.99/mo) simultaneously.',
            '**Same-Day Double Charge**: Notion charged twice ($12.00 each) on 2026-08-04 on Card 4288.',
          ],
          immediateActionItems: [
            'Cancel secondary Spotify Duo subscription and invite user to existing Family plan.',
            'Migrate Dropbox files to Google Drive and terminate secondary Dropbox account.',
            'Dispute or request refund on duplicate Notion charge from August 4.',
          ],
          potentialAnnualImpact: totalDupLoss,
          currency: 'USD',
        },
      };
    }

    // 4. Cloud & Developer Tools Audit
    if (q.includes('cloud') || q.includes('aws') || q.includes('developer') || q.includes('infrastructure')) {
      const cloudSubs = subscriptions.filter(
        (s) => s.category === 'cloud_infrastructure' || s.category === 'developer_tools'
      );
      const totalCloudAnnual = cloudSubs.reduce((sum, s) => sum + s.amount * 12, 0);

      return {
        id: `msg-ai-${Date.now()}`,
        role: 'assistant',
        timestamp,
        content: `You currently maintain **${cloudSubs.length} active cloud & developer subscriptions**, representing an annual commitment of **${formatCurrency(
          totalCloudAnnual
        )}/yr**. The largest driver is Amazon Web Services at $284.50/mo.`,
        structuredAuditReport: {
          headline: 'Cloud & Developer Tooling Spend Audit',
          executiveSummary:
            'Infrastructure spend is stable with steady usage on AWS. Transitioning baseline compute to 1-year commitments unlocks immediate savings.',
          keyFindings: [
            '**Amazon Web Services (Production)**: $284.50/mo ($3,414.00/yr) billed to Business Checking.',
            '**GitHub Copilot Business**: $19.00/mo ($228.00/yr) billed to Corporate Visa with high daily engagement.',
          ],
          immediateActionItems: [
            'Adopt AWS 1-Year Compute Savings Plans to save 28% (~$955.92/year).',
            'Review S3 lifecycle storage rules for old deployment logs.',
          ],
          potentialAnnualImpact: 955.92,
          currency: 'USD',
        },
      };
    }

    // 5. Unusual Spending Spike Query
    if (q.includes('spike') || q.includes('twilio') || q.includes('unusual') || q.includes('overage')) {
      return {
        id: `msg-ai-${Date.now()}`,
        role: 'assistant',
        timestamp,
        content: `I identified a significant **unusual spending spike on Twilio Communications** on September 4, 2026. Your invoice jumped to **$142.80**, which represents an **+852% surge** over your normal monthly baseline of **$15.00/mo** (Invoice INV-81204).`,
        structuredAuditReport: {
          headline: 'Forensic Audit: Unusual Usage Surge on Twilio Telephony',
          executiveSummary:
            'A one-time overage surge of +$127.80 occurred on Corporate Visa #4288, exceeding the 2.0x historical variance threshold.',
          keyFindings: [
            'Baseline Spend: $15.00/mo (observed steadily across July & August 2026)',
            'Spike Invoice: $142.80 on 2026-09-04 (INV-81204)',
            'Identified Surge: +$127.80 (+852.0% variance)',
          ],
          immediateActionItems: [
            'Audit Twilio Console -> Usage Logs to verify whether outbound SMS retry loops occurred.',
            'Configure automated spending alert limit at $35.00/mo.',
            'Dispatch courtesy refund request using the pre-filled dispute template in the Audit Dossier.',
          ],
          potentialAnnualImpact: 127.8,
          currency: 'USD',
        },
      };
    }

    // 6. Accidental Double Swipes & Duplicate Charges
    if (q.includes('double') || q.includes('swipe') || q.includes('double charge')) {
      return {
        id: `msg-ai-${Date.now()}`,
        role: 'assistant',
        timestamp,
        content: `I identified **2 accidental same-day double charges** in your transaction ledger:\n1. **GitHub Copilot Business**: Two identical debits of **$19.00** on September 2, 2026 on Corporate Visa 4288 (INV-771891 and INV-771892).\n2. **Notion Labs**: Two identical debits of **$12.00** on August 4, 2026 on Card 4288.\nTotal immediate cash recoverable: **$31.00**.`,
        structuredAuditReport: {
          headline: 'Forensic Ledger Audit: Same-Day Double Charge Errors',
          executiveSummary:
            'Card processing errors resulted in identical debits within the same 24-hour window on the exact same card.',
          keyFindings: [
            'GitHub Copilot Business: Duplicate debit ($19.00) on 2026-09-02 (tx-20260902-01 & tx-20260902-02)',
            'Notion Labs: Duplicate debit ($12.00) on 2026-08-04 (tx-20260804-01 & tx-20260804-02)',
            'Affected Card: Corporate Platinum Visa (4288)',
          ],
          immediateActionItems: [
            'Submit instant refund ticket to GitHub Billing with pre-filled template.',
            'Request statement credit on duplicate Notion swipe.',
          ],
          potentialAnnualImpact: 372.0,
          currency: 'USD',
        },
      };
    }

    // 7. Cancellation Letter / Figma Draft
    if (q.includes('letter') || q.includes('email') || q.includes('draft') || (q.includes('figma') && q.includes('cancel'))) {
      return {
        id: `msg-ai-${Date.now()}`,
        role: 'assistant',
        timestamp,
        content: `Here is a pre-drafted, professional cancellation email ready to send to eliminate your inactive Figma seat:\n\n` +
          `\`\`\`text\n` +
          `To: Figma Account Admin <admin@company.com>\n` +
          `Subject: License Seat De-provisioning Notice - Inactive Figma Seat\n\n` +
          `Hi Team,\n` +
          `SubGuard AI's audit scan detected that our Figma Organization seat ($45.00/mo on Card #4288) has been completely inactive for 104 consecutive days with zero document edits or user logins.\n\n` +
          `Please unassign this seat or convert the member to a Viewer-Restricted role in the Figma Admin Console to stop $540.00/year in unnecessary SaaS waste.\n\n` +
          `Best regards,\n` +
          `Finance & IT Operations\n` +
          `\`\`\``,
        structuredAuditReport: {
          headline: 'Pre-Drafted Vendor De-provisioning Notice',
          executiveSummary: 'Ready-to-dispatch cancellation email to reclaim $540.00/year in unused license waste.',
          keyFindings: [
            'Target Account: Figma Organization Seat ($45.00/mo)',
            'Dormancy: 104 days without activity (Threshold: 60 days)',
            'Annual Yield: $540.00/year savings',
          ],
          immediateActionItems: [
            'Copy email template above and send to license administrator.',
            'Confirm monthly invoice adjusts to $0 for this unassigned seat.',
          ],
          potentialAnnualImpact: 540.0,
          currency: 'USD',
        },
      };
    }

    // 8. Budget Cut / Optimization Playbook
    if (q.includes('cut') || q.includes('save') || q.includes('optimize') || q.includes('20%')) {
      const totalSavings = savingsOpportunities.reduce((s, op) => s + op.potentialAnnualSavings, 0);

      return {
        id: `msg-ai-${Date.now()}`,
        role: 'assistant',
        timestamp,
        content: `I synthesized a prioritized 4-step playbook that recovers **${formatCurrency(
          totalSavings
        )} in annualized savings**, exceeding your 20% spend reduction target without impacting team productivity.`,
        structuredAuditReport: {
          headline: `Spend Optimization Playbook: ${formatCurrency(totalSavings)} Annual Yield`,
          executiveSummary:
            'By de-provisioning inactive seats, consolidating duplicates, and adopting compute savings tiers, you can reduce recurring spend by ~27%.',
          keyFindings: savingsOpportunities.map(
            (op) => `**${op.title}**: Save ${formatCurrency(op.potentialAnnualSavings)}/yr (${op.effortLevel} effort)`
          ),
          immediateActionItems: [
            'Immediate: Cancel inactive Figma enterprise seat (Save $540.00/yr).',
            'Immediate: Cancel duplicate Spotify plan (Save $179.88/yr).',
            'Moderate: Sunset Dropbox in favor of existing Google One storage (Save $239.88/yr).',
            'Medium: Lock in AWS Compute Savings Plans (Save $955.92/yr).',
          ],
          potentialAnnualImpact: totalSavings,
          currency: 'USD',
        },
      };
    }

    // Default Overview Synthesis
    const totalLeakage = auditIssues.filter((i) => i.status === 'open').reduce((s, i) => s + i.impactAnnual, 0);

    return {
      id: `msg-ai-${Date.now()}`,
      role: 'assistant',
      timestamp,
      content: `I analyzed your portfolio of **${subscriptions.length} recurring subscriptions** and statement ledger. Total annual leakage of **${formatCurrency(
        totalLeakage
      )}** was detected across duplicate plans, inactive seats, and price creep.`,
      structuredAuditReport: {
        headline: 'Executive FinTech Audit Summary',
        executiveSummary:
          'SubGuard AI verified recurring patterns across all connected payment cards. Immediate action is recommended on 4 flagged anomalies.',
        keyFindings: [
          '**Netflix**: Silent price creep from $19.99 to $22.99 (+15.0%).',
          '**Spotify**: Duplicate subscriptions on Card 4288 and Virtual Card 9901.',
          '**Figma**: Inactive license seat with 0 sessions for 104 consecutive days.',
          '**Anthropic Claude**: Expiring 14-day trial converting to $200.00/mo in 48 hours.',
        ],
        immediateActionItems: [
          'De-provision inactive Figma license.',
          'Cancel duplicate Spotify account.',
          'Review Netflix subscription tier.',
          'Set Claude API token caps prior to auto-billing.',
        ],
        potentialAnnualImpact: totalLeakage,
        currency: 'USD',
      },
    };
  }

  /**
   * Helper to attach structured report when Gemini API responds
   */
  private static extractStructuredReportFromQuery(
    query: string,
    contextData: CopilotFinancialContextData
  ) {
    const q = query.toLowerCase();
    if (q.includes('save') || q.includes('cut') || q.includes('20%')) {
      const totalSavings = contextData.savingsOpportunities.reduce((s, op) => s + op.potentialAnnualSavings, 0);
      return {
        headline: 'AI Optimization Recommendations',
        executiveSummary: `Grounded in ${contextData.savingsOpportunities.length} active opportunities from your portfolio.`,
        keyFindings: contextData.savingsOpportunities.map(
          (op) => `**${op.title}**: Save ${formatCurrency(op.potentialAnnualSavings)}/yr`
        ),
        immediateActionItems: [
          'De-provision inactive Figma seat.',
          'Consolidate duplicate Spotify plans.',
          'Enable AWS Compute Savings Plans.',
        ],
        potentialAnnualImpact: totalSavings,
        currency: 'USD',
      };
    }
    return undefined;
  }
}
