import React, { useState } from 'react';
import {
  X,
  Printer,
  Copy,
  Check,
  Building2,
  Calendar,
  AlertTriangle,
  TrendingDown,
  CreditCard,
  Zap,
} from 'lucide-react';
import { useFinancialData } from '../../context/FinancialDataContext';
import { formatCurrency, formatDate } from '../../core/config/constants';

export const ExportAuditReportModal: React.FC = () => {
  const {
    isExportReportModalOpen,
    setIsExportReportModalOpen,
    auditSummary,
    auditIssues,
    savingsSummary,
    savingsOpportunities,
    subscriptionSummary,
    showToast,
  } = useFinancialData();

  const [copiedBrief, setCopiedBrief] = useState(false);

  if (!isExportReportModalOpen) return null;

  const handleCopyMarkdown = () => {
    const markdown = `# SubGuard AI - Executive Audit Dossier & Spend Optimization Report
**Entity:** Acme Cloud Technologies
**Audit Date:** September 9, 2026
**Classification:** Internal Executive Brief

---

## 1. Executive Summary
- **Financial Health Score:** ${auditSummary.healthScore}/100
- **Monthly Recurring Spend (MRR):** ${formatCurrency(subscriptionSummary.totalMonthlyNormalizedSpend)}
- **Annual Run-Rate Commitment (ARR):** ${formatCurrency(subscriptionSummary.totalAnnualSpend)}
- **Identified Spend Leakage:** ${formatCurrency(auditSummary.totalAnnualLeakage)}/yr (${auditSummary.totalOpenIssues} active anomalies)
- **Potential Realizable Savings:** ${formatCurrency(savingsSummary.totalIdentifiedAnnualSavings)}/yr

---

## 2. Critical Audit Anomalies Detected
${auditIssues
  .map(
    (issue, i) =>
      `${i + 1}. **${issue.title}** [${issue.severity.toUpperCase()}]
   - Target: ${issue.subscriptionName || 'Ledger Statement'}
   - Annual Leakage: ${formatCurrency(issue.impactAnnual)}/yr
   - Status: ${issue.status.toUpperCase()}
   - Summary: ${issue.description}`
  )
  .join('\n\n')}

---

## 3. Prioritized Autonomous Savings Opportunities
${savingsOpportunities
  .map(
    (op, i) =>
      `${i + 1}. **${op.title}**
   - Annual Yield: ${formatCurrency(op.potentialAnnualSavings)}/yr
   - Effort Level: ${op.effortLevel.toUpperCase()}
   - Implementation: ${op.recommendedNextStep}
   - Status: ${op.isApplied ? 'IMPLEMENTED' : 'PENDING'}`
  )
  .join('\n\n')}

---
*Report autonomously generated by SubGuard AI FinTech Intelligence Platform.*
`;

    navigator.clipboard.writeText(markdown);
    setCopiedBrief(true);
    showToast('Executive Brief Copied', 'Markdown report copied to clipboard. Ready for Slack or Notion.', 'success');
    setTimeout(() => setCopiedBrief(false), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  const getHealthGrade = (score: number) => {
    if (score >= 90) return { grade: 'A', color: '#10B981', label: 'Optimal' };
    if (score >= 75) return { grade: 'B', color: '#34D399', label: 'Good' };
    if (score >= 60) return { grade: 'C', color: '#F59E0B', label: 'Needs Attention' };
    if (score >= 40) return { grade: 'D', color: '#F87171', label: 'High Risk' };
    return { grade: 'F', color: '#EF4444', label: 'Critical Leakage' };
  };

  const grade = getHealthGrade(auditSummary.healthScore);

  return (
    <div
      className="modal-overlay"
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: 'rgba(0, 0, 0, 0.75)',
        backdropFilter: 'blur(10px)',
        WebkitBackdropFilter: 'blur(10px)',
        zIndex: 9000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
      }}
      onClick={() => setIsExportReportModalOpen(false)}
    >
      <div
        className="modal-content print-dossier-modal"
        style={{
          background: '#0B0F19',
          border: '1px solid var(--border-card)',
          borderRadius: 'var(--radius-lg)',
          width: '100%',
          maxWidth: 880,
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: 'var(--shadow-lg)',
          overflow: 'hidden',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Action Header (Hidden in Print) */}
        <div
          className="no-print"
          style={{
            padding: '16px 24px',
            borderBottom: '1px solid var(--border-subtle)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            background: 'rgba(255, 255, 255, 0.02)',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <span
              style={{
                fontSize: '0.75rem',
                fontWeight: 700,
                textTransform: 'uppercase',
                letterSpacing: '0.08em',
                color: '#818CF8',
                background: 'rgba(99, 102, 241, 0.15)',
                padding: '4px 8px',
                borderRadius: 'var(--radius-sm)',
              }}
            >
              Executive Deliverable
            </span>
            <span style={{ fontSize: '0.9rem', fontWeight: 600, color: '#E2E8F0' }}>
              Board-Ready Financial Audit Dossier
            </span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <button
              onClick={handleCopyMarkdown}
              className="btn-dismiss"
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 6,
                padding: '6px 12px',
                fontSize: '0.8rem',
                border: '1px solid var(--border-subtle)',
              }}
            >
              {copiedBrief ? <Check size={14} color="#34D399" /> : <Copy size={14} />}
              <span>{copiedBrief ? 'Copied Brief' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="scan-audit-btn"
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 6,
                padding: '6px 14px',
                fontSize: '0.8rem',
              }}
            >
              <Printer size={14} />
              <span>Print / Export PDF</span>
            </button>

            <button
              onClick={() => setIsExportReportModalOpen(false)}
              style={{
                background: 'none',
                border: 'none',
                color: '#94A3B8',
                cursor: 'pointer',
                padding: 6,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Printable Report Body */}
        <div
          className="printable-report"
          style={{
            padding: 32,
            overflowY: 'auto',
            display: 'flex',
            flexDirection: 'column',
            gap: 28,
            color: '#F8FAFC',
          }}
        >
          {/* Executive Letterhead */}
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'flex-start',
              borderBottom: '2px solid rgba(255, 255, 255, 0.1)',
              paddingBottom: 20,
            }}
          >
            <div>
              <div
                style={{
                  fontFamily: 'var(--font-display)',
                  fontSize: '1.4rem',
                  fontWeight: 800,
                  letterSpacing: '-0.02em',
                  color: '#FFFFFF',
                }}
              >
                SUBGUARD AI
                <span style={{ fontSize: '0.8rem', color: '#818CF8', marginLeft: 8 }}>
                  FINTECH AUDITOR
                </span>
              </div>
              <div style={{ fontSize: '0.82rem', color: '#94A3B8', marginTop: 4 }}>
                Autonomous Recurring Payment & Anomaly Forensic Dossier
              </div>
            </div>

            <div style={{ textAlign: 'right', fontSize: '0.8rem', color: '#94A3B8' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, justifyContent: 'flex-end', color: '#E2E8F0', fontWeight: 600 }}>
                <Building2 size={14} color="#818CF8" />
                Acme Cloud Technologies
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, justifyContent: 'flex-end', marginTop: 4 }}>
                <Calendar size={13} />
                Audited: {formatDate(new Date().toISOString())}
              </div>
              <div style={{ color: '#EF4444', fontWeight: 700, fontSize: '0.72rem', letterSpacing: '0.05em', marginTop: 4 }}>
                CONFIDENTIAL • BOARD & CFO REVIEW
              </div>
            </div>
          </div>

          {/* KPI Matrix Row */}
          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
              gap: 14,
            }}
          >
            {/* Health Score Pill */}
            <div
              style={{
                background: 'rgba(255, 255, 255, 0.03)',
                border: '1px solid var(--border-subtle)',
                borderRadius: 'var(--radius-md)',
                padding: '14px 16px',
                display: 'flex',
                alignItems: 'center',
                gap: 14,
              }}
            >
              <div
                style={{
                  width: 44,
                  height: 44,
                  borderRadius: '50%',
                  background: `${grade.color}22`,
                  border: `2px solid ${grade.color}`,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontWeight: 900,
                  fontSize: '1.2rem',
                  color: grade.color,
                }}
              >
                {grade.grade}
              </div>
              <div>
                <div style={{ fontSize: '0.72rem', textTransform: 'uppercase', color: '#94A3B8', fontWeight: 600 }}>
                  Audit Health
                </div>
                <div style={{ fontSize: '1.1rem', fontWeight: 700, color: '#F8FAFC' }}>
                  {auditSummary.healthScore}/100
                </div>
                <div style={{ fontSize: '0.72rem', color: grade.color }}>
                  {grade.label}
                </div>
              </div>
            </div>

            {/* MRR */}
            <div
              style={{
                background: 'rgba(255, 255, 255, 0.03)',
                border: '1px solid var(--border-subtle)',
                borderRadius: 'var(--radius-md)',
                padding: '14px 16px',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: '0.72rem', textTransform: 'uppercase', color: '#94A3B8', fontWeight: 600 }}>
                <CreditCard size={13} color="#6366F1" />
                Monthly Recurring
              </div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.15rem', fontWeight: 700, color: '#FFFFFF', marginTop: 4 }}>
                {formatCurrency(subscriptionSummary.totalMonthlyNormalizedSpend)}
              </div>
              <div style={{ fontSize: '0.72rem', color: '#94A3B8', marginTop: 2 }}>
                ARR: {formatCurrency(subscriptionSummary.totalAnnualSpend)}
              </div>
            </div>

            {/* Annual Leakage */}
            <div
              style={{
                background: 'rgba(239, 68, 68, 0.06)',
                border: '1px solid rgba(239, 68, 68, 0.25)',
                borderRadius: 'var(--radius-md)',
                padding: '14px 16px',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: '0.72rem', textTransform: 'uppercase', color: '#F87171', fontWeight: 600 }}>
                <AlertTriangle size={13} />
                Identified Leakage
              </div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.15rem', fontWeight: 700, color: '#F87171', marginTop: 4 }}>
                {formatCurrency(auditSummary.totalAnnualLeakage)}/yr
              </div>
              <div style={{ fontSize: '0.72rem', color: '#FCA5A5', marginTop: 2 }}>
                {auditSummary.totalOpenIssues} unaddressed flags
              </div>
            </div>

            {/* Savings Yield */}
            <div
              style={{
                background: 'rgba(16, 185, 129, 0.06)',
                border: '1px solid rgba(16, 185, 129, 0.25)',
                borderRadius: 'var(--radius-md)',
                padding: '14px 16px',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: '0.72rem', textTransform: 'uppercase', color: '#34D399', fontWeight: 600 }}>
                <TrendingDown size={13} />
                Realizable Savings
              </div>
              <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.15rem', fontWeight: 700, color: '#34D399', marginTop: 4 }}>
                {formatCurrency(savingsSummary.totalIdentifiedAnnualSavings)}/yr
              </div>
              <div style={{ fontSize: '0.72rem', color: '#6EE7B7', marginTop: 2 }}>
                {savingsSummary.opportunitiesCount} prioritized actions
              </div>
            </div>
          </div>

          {/* Section 1: Detected Anomalies Breakdown */}
          <div>
            <div
              style={{
                fontSize: '0.95rem',
                fontWeight: 700,
                color: '#F8FAFC',
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                marginBottom: 12,
                borderBottom: '1px solid var(--border-subtle)',
                paddingBottom: 8,
              }}
            >
              <AlertTriangle size={16} color="#EF4444" />
              1. Detailed Audit Findings & Forensic Evidence
            </div>

            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                <thead>
                  <tr style={{ background: 'rgba(255, 255, 255, 0.04)', textAlign: 'left', color: '#94A3B8' }}>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)' }}>Anomaly</th>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)' }}>Severity</th>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)' }}>Target Entity</th>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)', textAlign: 'right' }}>Annual Leakage</th>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)', textAlign: 'center' }}>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {auditIssues.map((issue) => (
                    <tr key={issue.id} style={{ borderBottom: '1px solid rgba(255, 255, 255, 0.04)' }}>
                      <td style={{ padding: '10px 10px', fontWeight: 600, color: '#E2E8F0' }}>
                        {issue.title}
                        <div style={{ fontSize: '0.73rem', color: '#94A3B8', fontWeight: 400, marginTop: 2 }}>
                          {issue.description}
                        </div>
                      </td>
                      <td style={{ padding: '10px 10px' }}>
                        <span
                          style={{
                            fontSize: '0.68rem',
                            fontWeight: 700,
                            padding: '2px 6px',
                            borderRadius: 'var(--radius-sm)',
                            textTransform: 'uppercase',
                            background:
                              issue.severity === 'critical'
                                ? 'rgba(239, 68, 68, 0.2)'
                                : issue.severity === 'high'
                                ? 'rgba(249, 115, 22, 0.2)'
                                : 'rgba(245, 158, 11, 0.2)',
                            color:
                              issue.severity === 'critical'
                                ? '#F87171'
                                : issue.severity === 'high'
                                ? '#FB923C'
                                : '#FBBF24',
                          }}
                        >
                          {issue.severity}
                        </span>
                      </td>
                      <td style={{ padding: '10px 10px', color: '#CBD5E1' }}>
                        {issue.subscriptionName || 'Ledger Debit'}
                      </td>
                      <td
                        style={{
                          padding: '10px 10px',
                          textAlign: 'right',
                          fontFamily: 'var(--font-mono)',
                          fontWeight: 700,
                          color: '#F87171',
                        }}
                      >
                        {formatCurrency(issue.impactAnnual)}/yr
                      </td>
                      <td style={{ padding: '10px 10px', textAlign: 'center' }}>
                        <span
                          style={{
                            fontSize: '0.72rem',
                            fontWeight: 600,
                            color: issue.status === 'resolved' ? '#34D399' : '#FBBF24',
                          }}
                        >
                          {issue.status === 'resolved' ? '✓ Resolved' : 'Open Flag'}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 2: Autonomous Savings Playbook */}
          <div>
            <div
              style={{
                fontSize: '0.95rem',
                fontWeight: 700,
                color: '#F8FAFC',
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                marginBottom: 12,
                borderBottom: '1px solid var(--border-subtle)',
                paddingBottom: 8,
              }}
            >
              <Zap size={16} color="#10B981" />
              2. Recommended Optimization Playbooks & ROI
            </div>

            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                <thead>
                  <tr style={{ background: 'rgba(255, 255, 255, 0.04)', textAlign: 'left', color: '#94A3B8' }}>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)' }}>Optimization</th>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)' }}>Effort</th>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)' }}>Recommended Action</th>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)', textAlign: 'right' }}>Projected Yield</th>
                    <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-subtle)', textAlign: 'center' }}>Execution</th>
                  </tr>
                </thead>
                <tbody>
                  {savingsOpportunities.map((op) => (
                    <tr key={op.id} style={{ borderBottom: '1px solid rgba(255, 255, 255, 0.04)' }}>
                      <td style={{ padding: '10px 10px', fontWeight: 600, color: '#E2E8F0' }}>
                        {op.title}
                      </td>
                      <td style={{ padding: '10px 10px' }}>
                        <span
                          style={{
                            fontSize: '0.68rem',
                            fontWeight: 700,
                            padding: '2px 6px',
                            borderRadius: 'var(--radius-sm)',
                            textTransform: 'uppercase',
                            background:
                              op.effortLevel === 'instant'
                                ? 'rgba(16, 185, 129, 0.15)'
                                : 'rgba(99, 102, 241, 0.15)',
                            color: op.effortLevel === 'instant' ? '#34D399' : '#818CF8',
                          }}
                        >
                          {op.effortLevel}
                        </span>
                      </td>
                      <td style={{ padding: '10px 10px', color: '#94A3B8', fontSize: '0.75rem' }}>
                        {op.recommendedNextStep}
                      </td>
                      <td
                        style={{
                          padding: '10px 10px',
                          textAlign: 'right',
                          fontFamily: 'var(--font-mono)',
                          fontWeight: 700,
                          color: '#34D399',
                        }}
                      >
                        +{formatCurrency(op.potentialAnnualSavings)}/yr
                      </td>
                      <td style={{ padding: '10px 10px', textAlign: 'center' }}>
                        <span
                          style={{
                            fontSize: '0.72rem',
                            fontWeight: 600,
                            color: op.isApplied ? '#34D399' : '#94A3B8',
                          }}
                        >
                          {op.isApplied ? '✓ Implemented' : 'Ready'}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Footer Signoff */}
          <div
            style={{
              marginTop: 10,
              paddingTop: 16,
              borderTop: '1px solid rgba(255, 255, 255, 0.1)',
              fontSize: '0.74rem',
              color: '#64748B',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
            }}
          >
            <div>
              Certified by SubGuard AI Autonomous Auditor • Deterministic Verification Engine v2.4
            </div>
            <div>Page 1 of 1 • Internal Audit Release</div>
          </div>
        </div>
      </div>
    </div>
  );
};
